"""The explicit engine state and the pure functions over it.

This is the no-hidden-state seam the charter requires: everything the pinned
oracle keeps in module globals (oracle pyreason.py:459-484) lives on one
EngineState object, constructed fresh and passed explicitly to the functions
that read or mutate it. The module-global facade (`pyreason/__init__.py`)
holds exactly one EngineState and delegates; tests and future embedders can
hold as many as they like.

Only the fields with a consumer in the current equivalence surface exist:
rules and facts (with their duplicate-name warn sets), the loaded graph and
its parsed attribute products, the IPL, the registered annotation/head/
closed-world collections, the program handle (None until reason() builds
one — the accessors' before-any-reason returns are banked observations),
the clause maps the trace views consult, and the settings object.

`reason()` here is the pinned dispatch (oracle pyreason.py:1497-1642):
first-run (or no program) builds a fresh Program over merged user+graph
facts — flipping atom_trace off when change storage is off, filtering the
ruleset under queries, reordering clauses when the graph is edge-heavy —
runs it, and clears the user fact lists so a later reason-again consumes
only newly added facts; the again arm re-drives the existing program.
"""

import sys
import time
import warnings

import networkx as nx

from . import _graph, _program
from ._settings import Settings
from .label import Label


class EngineState:
    """One engine's complete mutable state, explicit and resettable by
    construction — a fresh EngineState is a fresh engine."""

    def __init__(self):
        self.settings = Settings()
        # None (never loaded) vs empty are distinct pinned states: the
        # get-family accessors return None before any load.
        self.rules: list | None = None
        self.rules_name_set: set = set()
        self.node_facts: list | None = None
        self.edge_facts: list | None = None
        self.facts_name_set: set = set()
        self.program: "_program.Program | None" = None
        # Graph state — None until load_graph/load_graphml
        self.graph: "nx.DiGraph | None" = None
        self.graph_facts_node: list | None = None
        self.graph_facts_edge: list | None = None
        self.specific_graph_node_labels: dict | None = None
        self.specific_graph_edge_labels: dict | None = None
        # Inconsistent-predicate pairs — None until the first add/load
        self.ipl: list | None = None
        # Registered callables and closed-world predicate names
        self.annotation_functions: list = []
        self.head_functions: list = []
        self.closed_world_predicates: set = set()
        # Per-rule {new clause index: original} maps from the last reason()'s
        # clause reordering — the trace views render through them
        self.clause_maps: dict | None = None
        # The last reason()'s wall-clock stamp (oracle pyreason.py:1511) —
        # save_rule_trace and the stdout-redirect path embed it in their
        # file names; '' until the first reason(), like the pinned global.
        self.timestamp: str = ''


def add_rule(state: EngineState, pr_rule) -> None:
    """Add one constructed Rule's internal record to the state's rule list.

    Pinned semantics (oracle pyreason.py:632-649): the list is created on
    first add; a None name is autogenerated as rule_<position>; a repeated
    name warns (never raises) and still adds.
    """
    if state.rules is None:
        # The pin's list is a numba typed list (pyreason.py:639) — the
        # kind matters at the dispatch seam (_program.TypedRuleList)
        state.rules = _program.TypedRuleList()

    if pr_rule.rule.get_rule_name() is None:
        pr_rule.rule.set_rule_name(f'rule_{len(state.rules)}')

    if pr_rule.rule.get_rule_name() in state.rules_name_set:
        warnings.warn(f"Rule {pr_rule.rule.get_rule_name()} has already been added. Duplicate rule names will lead to an ambiguous rule trace.")

    state.rules_name_set.add(pr_rule.rule.get_rule_name())
    state.rules.append(pr_rule.rule)


def add_fact(state: EngineState, pyreason_fact) -> None:
    """Add one constructed Fact to the state's node- or edge-fact list.

    Pinned semantics (oracle pyreason.py:1133-1165): both lists are created
    together on first add; a None name is autogenerated as
    fact_<total position> and written back onto the caller's object; a
    repeated name warns (never raises) and still adds.
    """
    if state.node_facts is None:
        state.node_facts = []
    if state.edge_facts is None:
        state.edge_facts = []

    if pyreason_fact.name is None:
        pyreason_fact.name = f'fact_{len(state.node_facts) + len(state.edge_facts)}'

    if pyreason_fact.name in state.facts_name_set:
        warnings.warn(f"Fact {pyreason_fact.name} has already been added. Duplicate fact names will lead to an ambiguous node and atom traces.", stacklevel=2)

    state.facts_name_set.add(pyreason_fact.name)
    if pyreason_fact.type == 'node':
        state.node_facts.append(pyreason_fact)
    else:
        state.edge_facts.append(pyreason_fact)


def ipl_pair(pred1, pred2) -> tuple:
    """Build one IPL pair, guarding entry types the way the pinned typed-list
    append does: at the pin every IPL append lands in a numba
    typed.List(Tuple((label_type, label_type))) (pyreason.py:629 for the add
    path, yaml_parser.py:194 for the loader), and unbox_label reads each
    Label's _value as a numba string (label_type.py:86-94), so any non-str
    entry raises builtins.ValueError there. The pin's message is
    address-derived garbage (unreproducible even pin-vs-pin), so this guard
    raises the same type at the same seam with a stable, honest text instead
    — DIV-0002, adjudicated 2026-07-11 (docs/divergences/DIV-0002.md)."""
    for value in (pred1, pred2):
        if not isinstance(value, str):
            raise ValueError(
                f"IPL entries must be strings; got {type(value).__name__}: {value!r}")
    return (Label(pred1), Label(pred2))


def add_inconsistent_predicate(state: EngineState, pred1: str, pred2: str) -> None:
    """Add one inconsistent predicate pair (oracle pyreason.py:620-629): the
    list is created on first add; the pair is stored as Labels, in order.
    Non-string predicates raise ValueError at the append (ipl_pair — the
    DIV-0002 guard; the pin's typed-list append rejects them at the same
    point, after the empty list is already bound)."""
    if state.ipl is None:
        state.ipl = []
    state.ipl.append(ipl_pair(pred1, pred2))


def add_annotation_function(state: EngineState, function) -> None:
    """Register an annotation function, gating arity at registration (oracle
    pyreason.py:1415-1481): only the 2-arg (annotations, weights) and 6-arg
    extended signatures are callable from the reasoning loop, so anything
    else raises here with the pinned message."""
    py_func = getattr(function, 'py_func', function)
    nargs = py_func.__code__.co_argcount
    if nargs != 2 and nargs != 6:
        raise TypeError(
            f"Annotation function {py_func.__name__!r} must accept exactly 2 positional "
            f"args (annotations, weights) or exactly 6 positional args (annotations, "
            f"weights, qualified_nodes, qualified_edges, clause_labels, clause_variables); "
            f"got {nargs}."
        )
    state.annotation_functions.append(function)


def add_head_function(state: EngineState, function) -> None:
    """Register a head function — a silent append at the pin
    (pyreason.py:1484-1494), no signature gate."""
    state.head_functions.append(function)


def add_closed_world_predicate(state: EngineState, predicate_name: str) -> None:
    """Register a predicate as closed-world (oracle pyreason.py:1122-1130):
    wherever its bound is absent or the vacuous [0,1], satisfaction checks
    read it as [0,0]."""
    state.closed_world_predicates.add(predicate_name)


def reset(state: EngineState) -> None:
    """Clear the loaded facts, graph, and rules — the pinned PARTIAL clear
    (oracle pyreason.py:487-507), not a fresh engine: settings, the IPL, the
    clause maps, and the graph-parse products (graph facts + specific labels)
    all survive, and a live program is left half-cleared — its interp and
    graph nulled, the program object itself still handed out by
    get_logic_program (which is why get_time raises AttributeError on
    None.time after a with-program reset instead of answering 0)."""
    # Facts
    state.node_facts = None
    state.edge_facts = None
    state.facts_name_set.clear()
    state.closed_world_predicates = set()
    if state.program is not None:
        state.program.reset_facts()

    # Graph
    state.graph = None
    if state.program is not None:
        state.program.reset_graph()

    # Rules
    reset_rules(state)


def reset_rules(state: EngineState) -> None:
    """Clear the rules AND the registered annotation/head functions together
    (oracle pyreason.py:517-527); facts, graph, and settings stay loaded, and
    a live program keeps its interpretation (the observable contrast with
    reset(): get_time still answers afterwards)."""
    state.rules = None
    state.rules_name_set.clear()
    state.annotation_functions = []
    state.head_functions = []
    if state.program is not None:
        state.program.reset_rules()


def _peak_memory_mb() -> float:
    """The process's peak RSS in MB — the stdlib stand-in for the pinned
    memory_profiler backend (pyreason.py:1517-1526). Only the printed line's
    fixed text and having-a-number shape are contractual: the number itself
    is run-varying measurement in both engines and the harness canonicalizes
    exactly it (PEAK_MB_RE, harness/capture.py). ru_maxrss is bytes on
    darwin, KiB elsewhere."""
    import resource
    usage = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
    divisor = 1024 * 1024 if sys.platform == 'darwin' else 1024
    return usage / divisor


def _redirect_stdout_to_output_file(state: EngineState) -> None:
    """Rebind this process's stdout to ./{output_file_name}_{timestamp}.txt
    opened for append — the pinned side effect verbatim (pyreason.py:
    1513-1514, repeated at :1541-1542): cwd-relative, append mode, never
    restored and never flushed here (the harness's output_file probe
    flushes before reading)."""
    sys.stdout = open(
        f"./{state.settings.output_file_name}_{state.timestamp}.txt", "a")


def reason(state: EngineState, timesteps: int = -1, convergence_threshold: int = -1,
           convergence_bound_threshold: float = -1, queries=None,
           again: bool = False, restart: bool = True):
    """The reasoning entry point (oracle pyreason.py:1497-1531): stamp the
    file timestamp, rebind stdout when output_to_file is on, then dispatch —
    first-run (or no program yet) builds and runs a fresh program, again
    re-drives the existing one over the facts added since — each arm run
    bare or inside the memory-profile observation wrapper, whose peak-MB
    line prints AFTER the reasoning prints, onto whatever stdout then is."""
    settings = state.settings

    # Timestamp for saving files (pyreason.py:1511) — shared by the stdout
    # redirect and save_rule_trace's CSV names.
    state.timestamp = time.strftime('%Y%m%d-%H%M%S')

    if settings.output_to_file:
        _redirect_stdout_to_output_file(state)

    if not again or state.program is None:
        if settings.memory_profile:
            start_mem = _peak_memory_mb()
            interp = _reason(state, timesteps, convergence_threshold,
                             convergence_bound_threshold, queries)
            print(f"\nProgram used {_peak_memory_mb() - start_mem} MB of memory")
        else:
            interp = _reason(state, timesteps, convergence_threshold,
                             convergence_bound_threshold, queries)
    else:
        if settings.memory_profile:
            start_mem = _peak_memory_mb()
            interp = _reason_again(state, timesteps, restart, convergence_threshold,
                                   convergence_bound_threshold)
            print(f"\nProgram used {_peak_memory_mb() - start_mem} MB of memory")
        else:
            interp = _reason_again(state, timesteps, restart, convergence_threshold,
                                   convergence_bound_threshold)
    return interp


def _reason(state: EngineState, timesteps, convergence_threshold,
            convergence_bound_threshold, queries):
    settings = state.settings

    # The pinned _reason re-opens the SAME redirect file for append at its
    # own top (pyreason.py:1541-1542) — a second rebind, so every verbose
    # reasoning print below lands in the file. Reproduced including the
    # double-open: the first file object took no writes in either engine.
    if settings.output_to_file:
        _redirect_stdout_to_output_file(state)

    # A missing graph is an empty graph; missing rules are an error
    if state.graph is None:
        _graph.load_graph(state, nx.DiGraph())
        if settings.verbose:
            warnings.warn('Graph not loaded. Use `load_graph` to load the graphml file. Using empty graph')
    if state.rules is None:
        raise Exception('There are no rules, use `add_rule` or `add_rules_from_file`')

    if state.node_facts is None:
        state.node_facts = []
    if state.edge_facts is None:
        state.edge_facts = []
    if state.ipl is None:
        state.ipl = []

    # Graph-parse products join (rather than replace) any specific labels
    specific_node_labels = {}
    specific_edge_labels = {}
    for label_name, nodes in state.specific_graph_node_labels.items():
        if label_name in specific_node_labels:
            specific_node_labels[label_name].extend(nodes)
        else:
            specific_node_labels[label_name] = nodes
    for label_name, edges in state.specific_graph_edge_labels.items():
        if label_name in specific_edge_labels:
            specific_edge_labels[label_name].extend(edges)
        else:
            specific_edge_labels[label_name] = edges

    all_node_facts = list(state.node_facts) + list(state.graph_facts_node)
    all_edge_facts = list(state.edge_facts) + list(state.graph_facts_edge)

    # Atom trace cannot be on when change storage is off — the pinned engine
    # force-flips the PUBLIC knob (pyreason.py:1584-1585)
    if not settings.store_interpretation_changes:
        settings.atom_trace = False

    annotation_functions = tuple(state.annotation_functions)
    head_functions = tuple(state.head_functions)

    if settings.verbose:
        print('Filtering rules based on queries')
    if queries is not None:
        state.rules = _program.filter_ruleset(queries, state.rules)

    # Move node clauses ahead of edge clauses on edge-heavy graphs; the maps
    # let the trace views render clause columns in the author's order
    state.clause_maps = {r.get_rule_name(): {i: i for i in range(len(r.get_clauses()))}
                         for r in state.rules}
    if len(state.graph.edges) > len(state.graph.nodes):
        if settings.verbose:
            print('Optimizing rules by moving node clauses ahead of edge clauses')
        rules_copy = list(state.rules)
        # The pinned reorder arm rebuilds __rules as a FRESH numba typed
        # list (pyreason.py:1603) even when the query filter left it
        # empty — and an empty typed list still dispatches, so this rebuild
        # decides whether a query-emptied ruleset raises (TypedRuleList)
        state.rules = _program.TypedRuleList()
        for r in rules_copy:
            r, state.clause_maps[r.get_rule_name()] = _program.reorder_clauses(r)
            state.rules.append(r)

    state.program = _program.Program(
        state.graph, all_node_facts, all_edge_facts, state.rules, state.ipl,
        annotation_functions, head_functions, settings.reverse_digraph,
        settings.atom_trace, settings.save_graph_attributes_to_trace,
        settings.persistent, settings.inconsistency_check,
        settings.store_interpretation_changes, settings.update_mode,
        settings.allow_ground_rules, settings.parallel_computing,
        settings.fp_version)
    state.program.specific_node_labels = specific_node_labels
    state.program.specific_edge_labels = specific_edge_labels
    state.program.closed_world_predicates = [Label(p) for p in state.closed_world_predicates]

    interpretation = state.program.reason(timesteps, convergence_threshold,
                                          convergence_bound_threshold,
                                          settings.verbose)

    # Clear the user fact lists so reasoning again consumes only facts added
    # since (the pinned post-run clear, pyreason.py:1622-1624)
    state.node_facts = None
    state.edge_facts = None

    return interpretation


def _reason_again(state: EngineState, timesteps, restart, convergence_threshold,
                  convergence_bound_threshold):
    assert state.program is not None, 'To run `reason_again` you need to have reasoned once before'

    # _reason clears the fact lists to None on exit (and reset() does too),
    # so a resume with no fact added since converts None — the pinned
    # numba.typed.List(None) TypeError (oracle pyreason.py:1636), reproduced
    # message-for-message: a bare `again` is this raise, never a silent
    # zero-fact resume.
    if state.node_facts is None or state.edge_facts is None:
        raise TypeError('List() argument must be iterable')
    all_node_facts = list(state.node_facts)
    all_edge_facts = list(state.edge_facts)

    interpretation = state.program.reason_again(
        timesteps, restart, convergence_threshold, convergence_bound_threshold,
        all_node_facts, all_edge_facts, state.settings.verbose)

    return interpretation
