"""The explicit engine state and the pure add-functions over it.

This is the no-hidden-state seam the charter requires: everything the pinned
oracle keeps in module globals (oracle pyreason.py:459-484) lives on one
EngineState object, constructed fresh and passed explicitly to the functions
that read or mutate it. The module-global facade (`pyreason/__init__.py`)
holds exactly one EngineState and delegates; tests and future embedders can
hold as many as they like.

Only the fields with a consumer in the current equivalence surface exist:
rules and facts (with their duplicate-name warn sets), the program handle
(None until reason() lands — the accessors' before-any-reason returns are
banked observations), and the settings object. Graph, IPL, and registered-
function state land with the packets whose cases consume them.
"""

import warnings

from ._settings import Settings


class EngineState:
    """One engine's complete mutable state, explicit and resettable by
    construction — a fresh EngineState is a fresh engine."""

    def __init__(self):
        self.settings = Settings()
        # None (never loaded) vs empty are distinct pinned states: the
        # get-family accessors return None before any load.
        self.rules: list | None = None
        self.rules_name_set: set = set()
        self.node_facts: list | None = None
        self.edge_facts: list | None = None
        self.facts_name_set: set = set()
        self.program = None


def add_rule(state: EngineState, pr_rule) -> None:
    """Add one constructed Rule's internal record to the state's rule list.

    Pinned semantics (oracle pyreason.py:632-649): the list is created on
    first add; a None name is autogenerated as rule_<position>; a repeated
    name warns (never raises) and still adds.
    """
    if state.rules is None:
        state.rules = []

    if pr_rule.rule.get_rule_name() is None:
        pr_rule.rule.set_rule_name(f'rule_{len(state.rules)}')

    if pr_rule.rule.get_rule_name() in state.rules_name_set:
        warnings.warn(f"Rule {pr_rule.rule.get_rule_name()} has already been added. Duplicate rule names will lead to an ambiguous rule trace.")

    state.rules_name_set.add(pr_rule.rule.get_rule_name())
    state.rules.append(pr_rule.rule)


def add_fact(state: EngineState, pyreason_fact) -> None:
    """Add one constructed Fact to the state's node- or edge-fact list.

    Pinned semantics (oracle pyreason.py:1133-1165): both lists are created
    together on first add; a None name is autogenerated as
    fact_<total position> and written back onto the caller's object; a
    repeated name warns (never raises) and still adds.
    """
    if state.node_facts is None:
        state.node_facts = []
    if state.edge_facts is None:
        state.edge_facts = []

    if pyreason_fact.name is None:
        pyreason_fact.name = f'fact_{len(state.node_facts) + len(state.edge_facts)}'

    if pyreason_fact.name in state.facts_name_set:
        warnings.warn(f"Fact {pyreason_fact.name} has already been added. Duplicate fact names will lead to an ambiguous node and atom traces.", stacklevel=2)

    state.facts_name_set.add(pyreason_fact.name)
    if pyreason_fact.type == 'node':
        state.node_facts.append(pyreason_fact)
    else:
        state.edge_facts.append(pyreason_fact)
