"""The public Fact constructor — fact-text DSL in, parsed fact out.

Signature and semantics match the pinned oracle constructor
(oracle scripts/facts/fact.py): parsing happens eagerly in __init__, so a
malformed fact_text raises here; the parsed fields (pred as a Label,
component, bound as an Interval, type 'node'/'edge') ride as attributes —
the surface the equivalence harness fingerprints.
"""

from . import _fact_parser
from .label import Label


class Fact:
    """One fact parsed from text format.

    Format: 'Predicate(component)' or 'Predicate(component):bound', where the
    bound is True/False (case-insensitive), '[lower,upper]' with both values
    in [0, 1], or omitted (defaults to True); a leading '~' negates. A single
    component makes a node fact, two comma-separated components an edge fact.

    :param fact_text: the fact in text format
    :param name: the fact's name (appears in the trace); autogenerated at add
        time when None
    :param start_time: the timestep at which this fact becomes active
    :param end_time: the last timestep this fact is active
    :param static: whether the fact holds for the entire program (start_time
        and end_time are ignored when set)
    """

    def __init__(self, fact_text: str, name: str | None = None, start_time: int = 0,
                 end_time: int = 0, static: bool = False):
        pred, component, bound, fact_type = _fact_parser.parse_fact(fact_text)
        self.name = name
        self.start_time = start_time
        self.end_time = end_time
        self.static = static
        self.pred = Label(pred)
        self.component = component
        self.bound = bound
        self.type = fact_type

    def __str__(self):
        s = f'{self.pred}({self.component}) : {self.bound}'
        if self.static:
            s += ' | static'
        else:
            s += f' | start: {self.start_time} -> end: {self.end_time}'
        return s
