"""The public Rule constructor — text DSL in, parsed rule out.

Signature and semantics match the pinned oracle constructor
(oracle scripts/rules/rule.py): parsing happens eagerly in __init__, so a
malformed rule_text raises here, and the parsed internal record rides on
`self.rule` — the attribute the add-rule seam and the equivalence harness
both consume.
"""

from . import _rule_parser


class Rule:
    """One rule parsed from text format, e.g.
    'pred1(x,y) : [0.2, 1] <- pred2(a, b) : [1,1], pred3(b, c)'.

    :param rule_text: the rule in text format
    :param name: the rule's name (appears in the rule trace); autogenerated
        at add time when None
    :param infer_edges: whether to infer new edges after an edge rule fires
        (silently forced off for node rules)
    :param set_static: whether the head atom becomes static when the rule fires
    :param custom_thresholds: a list (one per clause) or a clause-index dict
        of Threshold objects; None means the ANY defaults
    :param weights: a list of clause weights handed to an annotation function;
        None means all ones
    """

    def __init__(self, rule_text: str, name: str | None = None, infer_edges: bool = False,
                 set_static: bool = False, custom_thresholds=None, weights=None):
        self.rule = _rule_parser.parse_rule(rule_text, name, custom_thresholds,
                                            infer_edges, set_static, weights)
